language: node_js
node_js:
  - "16"

install:
  - npm install

before_script：
  - git checkout master
  - echo "----------123456----------" >>      README.md
  - git add README.md
  - git commit -m "Commit from TravisCI"
   - git push origin master

script:
  - npm run build

after_success:
  - cd ./dist
  - git init
  - git config --global user.name "${U_NAME}"
  - git config --global user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Automatically update from travis-ci"
  - git push --quiet --force  "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}

branches:
  only:
    - master
